from app.state.store import STATE
from app.agents.planner import generate_phases
from app.agents.task_expander import expand_phase
from app.agents.verifier import verify_phase
from app.utils.github import create_issue

def main():
    print("\n=== execution_orecal : Execution Oracle CLI ===\n")

    # -----------------------------
    # ONE-TIME PROJECT CONTEXT
    # -----------------------------
    STATE["project"] = input("What do you want to build?\n> ").strip()
    STATE["tech"] = input("Tech stack?\n> ").strip()
    STATE["features"] = input("Core features?\n> ").strip()
    STATE["platform"] = input("Platform (web/mobile)?\n> ").strip()

    print("\nPlanning execution phases...\n")

    # INTERACTIVE PLANNING LOOP
    while True:
        STATE["phases"] = generate_phases(
            STATE["project"],
            STATE["tech"],
            STATE["features"],
            STATE["platform"]
        )

        if not STATE["phases"]:
            print("❌ Failed to generate phases. Retrying...")
            continue

        print("\nHere is your execution plan:\n")
        for i, p in enumerate(STATE["phases"]):
            print(f"{i+1}. {p}")

        print("\n[A]pprove Plan")
        print("[R]egenerate Plan")
        print("[E]dit Plan Manually")
        
        choice = input("\nChoice (A/R/E): ").strip().upper()

        if choice == 'A':
            break
        elif choice == 'R':
            print("\n♻️ Regenerating plan...")
            continue
        elif choice == 'E':
            print("\nEnter phases manually (one per line). End with an empty line.")
            new_phases = []
            while True:
                line = input("> ").strip()
                if not line:
                    break
                # Ensure format "Phase X: Name"
                if not line.lower().startswith("phase"):
                    line = f"Phase {len(new_phases)+1}: {line}"
                new_phases.append(line)
            
            if new_phases:
                STATE["phases"] = new_phases
                break
            else:
                print("❌ No phases entered. Keeping original plan.")

    # -----------------------------
    # GITHUB REPO (ONCE)
    # -----------------------------
    STATE["repo_url"] = input("\nPaste PUBLIC GitHub repo URL:\n> ").strip()
    
    # Ask about GitHub Issues
    create_issues = input("Create GitHub Issues for tasks? (y/n): ").strip().lower() == 'y'

    print("\nNOTE:")
    print("- Repo must be PUBLIC")
    print("- You must PUSH commits to GitHub")
    print("- execution_orecal checks ONLY the latest commit message\n")

    # -----------------------------
    # EXECUTION LOOP
    # -----------------------------
    while STATE["current_phase"] < len(STATE["phases"]):
        idx = STATE["current_phase"]
        phase_line = STATE["phases"][idx]

        # Extract phase number + name
        try:
            # Handle user manually entered phases that might not have colons ideally
            if ":" in phase_line:
                phase_number_str = phase_line.split(":")[0].replace("Phase", "").strip()
                phase_name = phase_line.split(":", 1)[1].strip()
                phase_number = int(phase_number_str) if phase_number_str.isdigit() else idx + 1
            else:
                phase_number = idx + 1
                phase_name = phase_line
        except Exception:
            print("❌ Parsing error for phase:", phase_line)
            # Fallback
            phase_number = idx + 1
            phase_name = phase_line

        print(f"\n=== {phase_line} ===\n")

        # Generate REAL tasks (Context Aware)
        tasks, expected_commit = expand_phase(
            phase_number,
            phase_name,
            STATE["project"],
            STATE["tech"],
            STATE["features"]
        )

        if not tasks:
            print("❌ No tasks generated. This should not happen.")
            return

        print("Tasks:")
        for t in tasks:
            print(f"- {t}")

        # Create GitHub Issues if requested
        if create_issues:
            print("\nCreating GitHub Issues...")
            for t in tasks:
                success, url = create_issue(STATE["repo_url"], title=f"Phase {phase_number}: {t}", body=f"Task generated by execution_orecal for Phase {phase_number}.")
                if success:
                    print(f"  ✅ Issue created: {url}")
                else:
                    print(f"  ❌ Failed to create issue: {url}")

        print("\nExpected commit message (intent-based):")
        print(expected_commit)

        print("\nAfter completing tasks:")
        print("1. Commit with the message above")
        print("2. PUSH the commit to GitHub")
        print('3. Type "next-phase"\n')

        cmd = input('> ').strip()

        if cmd != "next-phase":
            print('❌ Invalid command. Type exactly: next-phase')
            continue

        # -----------------------------
        # GITHUB VERIFICATION
        # -----------------------------
        success, message = verify_phase(STATE["repo_url"], phase_number)

        if success:
            print("\n✅ Phase verified successfully.")
            print(message)
            STATE["current_phase"] += 1
        else:
            print("\n❌ Phase NOT verified.")
            print(message)
            print("Fix the commit message, push again, then type next-phase.")

    print("\n🎉 All phases completed.")
    print("execution_orecal finished execution successfully.")


if __name__ == "__main__":
    main()
